--- Makefile.in.orig	2011-04-17 15:48:31.598864421 +0200
+++ Makefile.in	2011-04-17 15:49:01.814864688 +0200
@@ -49,7 +49,7 @@
 fetch: src.downloaded
 
 Makefile: configure.in set_soenv.in Makefile.in
-	./autogen.sh
+	NOCONFIGURE=1 ./autogen.sh
 
 check: Makefile dmake/dmake@EXEEXT@ fetch
 	@. ./*[Ee]nv.[Ss]et.sh && \
